name: Disease
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - _r-mutex=1.0.0
  - anyio=4.6.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - async-lru=2.0.4
  - attrs=24.3.0
  - babel=2.16.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=6.2.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - comm=0.2.1
  - contourpy=1.3.1
  - cycler=0.11.0
  - debugpy=1.8.11
  - decorator=5.1.1
  - defusedxml=0.7.1
  - executing=0.8.3
  - expat=2.6.4
  - fonttools=4.55.3
  - freetype=2.12.1
  - h11=0.14.0
  - h5py=3.12.1
  - hdf5=1.14.5
  - httpcore=1.0.2
  - httpx=0.27.0
  - icc_rt=2022.1.0
  - icu=73.1
  - idna=3.7
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.30.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - jpeg=9e
  - json5=0.9.25
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.3.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.2
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - kt-legacy=1.0.5
  - lcms2=2.16
  - lerc=4.0.0
  - libdeflate=1.22
  - libffi=3.4.4
  - libpng=1.6.39
  - libpq=17.4
  - libsodium=1.0.18
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - m2w64-bwidget=1.9.10
  - m2w64-bzip2=1.0.6
  - m2w64-expat=2.1.1
  - m2w64-fftw=3.3.4
  - m2w64-flac=1.3.1
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gettext=0.19.7
  - m2w64-gmp=6.1.0
  - m2w64-gsl=2.1
  - m2w64-libiconv=1.14
  - m2w64-libjpeg-turbo=1.4.2
  - m2w64-libogg=1.3.2
  - m2w64-libpng=1.6.21
  - m2w64-libsndfile=1.0.26
  - m2w64-libtiff=4.0.6
  - m2w64-libvorbis=1.3.5
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - m2w64-libxml2=2.9.3
  - m2w64-mpfr=3.1.4
  - m2w64-openblas=0.2.19
  - m2w64-pcre=8.38
  - m2w64-speex=1.2rc2
  - m2w64-speexdsp=1.2rc3
  - m2w64-tcl=8.6.5
  - m2w64-tk=8.6.5
  - m2w64-tktable=2.10
  - m2w64-wineditline=2.101
  - m2w64-xz=5.2.2
  - m2w64-zlib=1.2.8
  - markupsafe=3.0.2
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.6
  - mistune=3.1.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - msys2-conda-epoch=20160418
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - notebook=7.3.2
  - notebook-shim=0.2.4
  - numexpr=2.10.1
  - numpy=2.0.1
  - numpy-base=2.0.1
  - openjpeg=2.5.2
  - overrides=7.4.0
  - packaging=24.2
  - pandas=2.2.3
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pillow=11.1.0
  - pip=25.0
  - platformdirs=3.10.0
  - prometheus_client=0.21.0
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyparsing=3.2.0
  - pyqt=6.7.1
  - pyqt6-sip=13.9.1
  - pysocks=1.7.1
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-json-logger=3.2.1
  - python-tzdata=2023.3
  - pytz=2024.1
  - pywin32=308
  - pywinpty=2.0.15
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qtbase=6.7.2
  - qtdeclarative=6.7.2
  - qtsvg=6.7.2
  - qttools=6.7.2
  - qtwebchannel=6.7.2
  - qtwebsockets=6.7.2
  - r-assertthat=0.2.1
  - r-base=3.6.1
  - r-base64enc=0.1_3
  - r-cli=1.1.0
  - r-config=0.3
  - r-crayon=1.3.4
  - r-fansi=0.4.0
  - r-generics=0.0.2
  - r-glue=1.3.1
  - r-jsonlite=1.6
  - r-keras=2.2.4.1
  - r-lattice=0.20_38
  - r-magrittr=1.5
  - r-matrix=1.2_17
  - r-pillar=1.3.1
  - r-pkgconfig=2.0.2
  - r-processx=3.3.0
  - r-ps=1.3.0
  - r-purrr=0.3.2
  - r-r6=2.4.0
  - r-rcpp=1.0.1
  - r-reticulate=1.12
  - r-rlang=0.3.4
  - r-rstudioapi=0.10
  - r-tensorflow=1.13.1
  - r-tfruns=1.4
  - r-tibble=2.1.1
  - r-tidyselect=0.2.5
  - r-utf8=1.1.4
  - r-whisker=0.3_2
  - r-yaml=2.2.0
  - r-zeallot=0.1.0
  - referencing=0.30.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.22.3
  - scipy=1.15.1
  - seaborn=0.13.2
  - send2trash=1.8.2
  - setuptools=75.8.0
  - sip=6.10.0
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.45.3
  - stack_data=0.2.0
  - tbb=2021.8.0
  - terminado=0.17.1
  - tinycss2=1.4.0
  - tk=8.6.14
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025a
  - unicodedata2=15.1.0
  - urllib3=2.3.0
  - vc=14.42
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zstd=1.5.6

